name: ci-checks
on: [push]
jobs:
  check-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check --continue
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@47c2b1d0baf4e9cd2e03bdf29325f1e9ec28994a # v3.0.1
        with:
          report_paths: 'build/test-results/test/TEST-*.xml'
          check_name: "JUnit Test Report (Linux)"
  check-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check --continue
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@47c2b1d0baf4e9cd2e03bdf29325f1e9ec28994a # v3.0.1
        with:
          report_paths: 'build/test-results/test/TEST-*.xml'
          check_name: "JUnit Test Report (MacOS)"
  publish-linux:
    needs:
      - check-linux
      - check-macos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - run: mv build/graal/ghpush build/distributions/ghpush-linux
      - uses: actions/upload-artifact@v3
        with:
          name: distributions
          path: build/distributions/
      - name: Create GitHub Release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: ghpush ${{ github.ref_name }}
          files: build/distributions/*
      - name: Open PR in Homebrew tap (AlexLandau/homebrew-ghpush)
        if: ${{ github.ref_type == 'tag' }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_TOKEN }}
        run: |
          git config --global user.email "alandau@cs.stanford.edu"
          git config --global user.name "Alex Landau (ghpush automation)"
          brew tap AlexLandau/ghpush
          brew bump-formula-pr -f --version=${{ github.ref_name }} --no-browse --no-audit AlexLandau/ghpush/ghpush
  publish-macos:
    needs:
      - check-linux
      - check-macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - run: mv build/graal/ghpush build/distributions/ghpush-macos
      - uses: actions/upload-artifact@v3
        with:
          name: distributions
          path: build/distributions/ghpush-macos
      - name: Create GitHub Release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: ghpush ${{ github.ref_name }}
          files: build/distributions/ghpush-macos
